In [8]:
import numpy as np
array=np.array([[1,2,3],[4,5,6]])
array.shape
array.ndim

2

In [10]:
array=np.arange(3,21,1)
print(array)
print(array.shape)
print(array.ndim)
array.reshape(3,6)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(18,)
1


array([[ 3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20]])

In [11]:
data=np.arange(6).reshape(2,3)
data

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
arr1=np.arange(6).reshape(3,2)
arr2=np.ones((2,3))
print(arr1)
arr2

[[0 1]
 [2 3]
 [4 5]]


array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
print(np.dot(arr1,arr2))

[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]


In [31]:
#arr1*arr2
np.matmul(arr1,arr2)

array([[1., 1., 1.],
       [5., 5., 5.],
       [9., 9., 9.]])

In [33]:
np.random.rand(3,3)

array([[0.86700539, 0.74883794, 0.03392123],
       [0.34132474, 0.02773637, 0.01509156],
       [0.15578432, 0.8358214 , 0.70897239]])