BatchNorm1D:可用作卷积和全连接操作的批归一化函数，根据当前批次数据按通道计算的均值和方差进行归一化。
input: 形状为（批大小，通道数）的2-D Tensor 或（批大小, 通道数，长度）的3-D Tensor。

BatchNorm2D是计算4d的批归一化函数，

In [20]:
import paddle

paddle.seed(120)
x_data = paddle.rand(shape=(2, 1),dtype='float32')
print(x_data)
batch_norm = paddle.nn.BatchNorm1D(1)# 通道数
batch_norm_out = batch_norm(x_data)

print(batch_norm_out.numpy())

dict=batch_norm.state_dict()
for key in dict:
    print(f'{key} {dict[key].numpy()}')



Tensor(shape=[2, 1], dtype=float32, place=CUDAPlace(0), stop_gradient=True,
       [[0.00269735],
        [0.20389390]])
[[-0.9995063 ]
 [ 0.99950624]]
weight [1.]
bias [0.]
_mean [0.01032957]
_variance [0.902024]


d:\tool\python36\lib\site-packages\paddle\nn\layer\norm.py:648: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")


In [42]:
avg=paddle.mean(x_data)
variance=paddle.std(x_data)
print('x_data:%s\n avg:%f std:%f'%(x_data.numpy(),avg.numpy(),variance.numpy()))
v2=paddle.sum(paddle.square(x_data-avg))/2
# 不能这样用，因为sum后只有一维，求
v1=paddle.mean(paddle.sum(paddle.square(x_data-avg)))
print()
print('自己求标准差：%f 用mean(sum)求：%f'%(v2.numpy(),v1.numpy()))
res=(x_data-avg)/paddle.sqrt(v2+1e-5)
print(res.numpy())

x_data:[[0.00269735]
 [0.2038939 ]]
 avg:0.103296 std:0.142267

自己求标准差：0.010120 用mean(sum)求：0.020240
[[-0.9995063]
 [ 0.9995063]]


In [40]:
import paddle

x = paddle.to_tensor([[[1., 2., 3., 4.],
                       [5., 6., 7., 8.],
                       [9., 10., 11., 12.]],
                      [[13., 14., 15., 16.],
                       [17., 18., 19., 20.],
                       [21., 22., 23., 24.]]])
print(x.shape)
out1 = paddle.mean(x)
# [12.5]
out2 = paddle.mean(x, axis=-1)
# [[ 2.5  6.5 10.5]
#  [14.5 18.5 22.5]]
out3 = paddle.mean(x, axis=-1, keepdim=True)
# [[[ 2.5]
#   [ 6.5]
#   [10.5]]
#  [[14.5]
#   [18.5]
#   [22.5]]]
out4 = paddle.mean(x, axis=[0, 2])

[2, 3, 4]
