In [1]:
import numpy as np
from sklearn.model_selection import KFold
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
Y = np.array([1, 2, 3, 4])
kf = KFold(n_splits=2)
print( kf.get_n_splits(X))

2


In [7]:
for train_index,test_index in kf.split(X):
    print(f'index {train_index},{test_index}')
    x_train,x_test=X[train_index],X[test_index]
    print(x_train,x_test)

index [2 3],[0 1]
[[1 2]
 [3 4]] [[1 2]
 [3 4]]
index [0 1],[2 3]
[[1 2]
 [3 4]] [[1 2]
 [3 4]]


In [4]:
n=np.arange(20)
for train_index,test_index in kf.split(n):
    print(f'index {train_index},{test_index}')
    x_train,x_test=n[train_index],n[test_index]
    print(x_train,x_test)

index [10 11 12 13 14 15 16 17 18 19],[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19] [0 1 2 3 4 5 6 7 8 9]
index [0 1 2 3 4 5 6 7 8 9],[10 11 12 13 14 15 16 17 18 19]
[0 1 2 3 4 5 6 7 8 9] [10 11 12 13 14 15 16 17 18 19]


In [8]:
kf2=KFold(n_splits=5)
for id,(train_index,test_index) in enumerate(kf2.split(n)):
    print(f'{id} {train_index} {test_index}')

0 [ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] [0 1 2 3]
1 [ 0  1  2  3  8  9 10 11 12 13 14 15 16 17 18 19] [4 5 6 7]
2 [ 0  1  2  3  4  5  6  7 12 13 14 15 16 17 18 19] [ 8  9 10 11]
3 [ 0  1  2  3  4  5  6  7  8  9 10 11 16 17 18 19] [12 13 14 15]
4 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] [16 17 18 19]
