In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [9]:
import numpy as np

In [11]:
r=np.random.randint(0,10,(1,4))
r.reshape((4,1))

array([[4],
       [4],
       [7],
       [7]])

In [12]:

x=np.array([1,2,3,4]).reshape((4,1))
y=np.array([2,4,6,8]).reshape((4,1))
x
y

array([[1],
       [2],
       [3],
       [4]])

array([[2],
       [4],
       [6],
       [8]])

In [31]:
a=0
b=0
n=len(x)
lr=0.001
for i in range(1000):
    y_predict=a*x+b
    #print(y_predict)
    loss=0        
    loss=(y_predict-y)*(y_predict-y)
    #print('loss=',loss)
    avg_loss=np.sum(loss,axis=0)/(2*n)
    print('avg_loss=',avg_loss)
    da=np.sum((y_predict-y)*x,axis=0)/n
    db=np.sum(y_predict-y,axis=0)/n
    #print('da=',da)
    a=a-lr*da
    b=b-lr*db
    print('{}x+{}'.format(a,b))
    if avg_loss<1e-5:
        print('准确度已经很高，break')
        break
            

avg_loss= [15.]
[0.015]x+[0.005]
avg_loss= [14.75104375]
[0.029875]x+[0.0099575]
avg_loss= [14.50622771]
[0.04462604]x+[0.01487286]
avg_loss= [14.26548303]
[0.05925417]x+[0.01974642]
avg_loss= [14.02874199]
[0.07376039]x+[0.02457854]
avg_loss= [13.79593801]
[0.08814574]x+[0.02936956]
avg_loss= [13.56700561]
[0.10241123]x+[0.03411982]
avg_loss= [13.34188041]
[0.11655784]x+[0.03882967]
avg_loss= [13.12049909]
[0.13058659]x+[0.04349945]
avg_loss= [12.90279939]
[0.14449844]x+[0.04812948]
avg_loss= [12.68872007]
[0.15829438]x+[0.05272011]
avg_loss= [12.47820093]
[0.17197537]x+[0.05727165]
avg_loss= [12.27118275]
[0.18554237]x+[0.06178444]
avg_loss= [12.06760732]
[0.19899634]x+[0.0662588]
avg_loss= [11.86741738]
[0.21233822]x+[0.07069505]
avg_loss= [11.67055662]
[0.22556895]x+[0.07509351]
avg_loss= [11.47696968]
[0.23868945]x+[0.0794545]
avg_loss= [11.28660211]
[0.25170064]x+[0.08377832]
avg_loss= [11.09940037]
[0.26460344]x+[0.08806529]
avg_loss= [10.91531181]
[0.27739875]x+[0.09231571]
avg

avg_loss= [0.07887539]
[1.69932831]x+[0.54422077]
avg_loss= [0.07802167]
[1.70022279]x+[0.54442822]
avg_loss= [0.07718202]
[1.70111005]x+[0.54463324]
avg_loss= [0.07635619]
[1.70199014]x+[0.54483583]
avg_loss= [0.07554395]
[1.70286313]x+[0.54503602]
avg_loss= [0.07474509]
[1.70372906]x+[0.54523383]
avg_loss= [0.07395938]
[1.70458801]x+[0.54542927]
avg_loss= [0.07318659]
[1.70544003]x+[0.54562237]
avg_loss= [0.07242652]
[1.70628517]x+[0.54581315]
avg_loss= [0.07167896]
[1.7071235]x+[0.54600162]
avg_loss= [0.07094369]
[1.70795507]x+[0.54618781]
avg_loss= [0.07022051]
[1.70877994]x+[0.54637174]
avg_loss= [0.06950923]
[1.70959816]x+[0.54655341]
avg_loss= [0.06880963]
[1.71040979]x+[0.54673287]
avg_loss= [0.06812154]
[1.71121488]x+[0.54691011]
avg_loss= [0.06744475]
[1.7120135]x+[0.54708516]
avg_loss= [0.06677908]
[1.71280568]x+[0.54725804]
avg_loss= [0.06612434]
[1.71359149]x+[0.54742877]
avg_loss= [0.06548036]
[1.71437099]x+[0.54759736]
avg_loss= [0.06484695]
[1.71514421]x+[0.54776384]
av

[1.78200259]x+[0.55647211]
avg_loss= [0.02976767]
[1.78224639]x+[0.55646063]
avg_loss= [0.02970832]
[1.78248839]x+[0.55644855]
avg_loss= [0.02964982]
[1.7827286]x+[0.55643588]
avg_loss= [0.02959217]
[1.78296705]x+[0.55642263]
avg_loss= [0.02953534]
[1.78320374]x+[0.55640879]
avg_loss= [0.02947933]
[1.78343869]x+[0.55639437]
avg_loss= [0.02942412]
[1.78367191]x+[0.55637938]
avg_loss= [0.02936969]
[1.78390343]x+[0.55636382]
avg_loss= [0.02931605]
[1.78413324]x+[0.55634769]
avg_loss= [0.02926316]
[1.78436137]x+[0.55633101]
avg_loss= [0.02921102]
[1.78458784]x+[0.55631378]
avg_loss= [0.02915962]
[1.78481264]x+[0.556296]
avg_loss= [0.02910895]
[1.78503581]x+[0.55627767]
avg_loss= [0.02905899]
[1.78525734]x+[0.5562588]
avg_loss= [0.02900973]
[1.78547727]x+[0.5562394]
avg_loss= [0.02896116]
[1.78569559]x+[0.55621947]
avg_loss= [0.02891326]
[1.78591232]x+[0.55619901]
avg_loss= [0.02886603]
[1.78612748]x+[0.55617803]
avg_loss= [0.02881946]
[1.78634108]x+[0.55615653]
avg_loss= [0.02877354]
[1.78

avg_loss= [0.02557625]
[1.80615189]x+[0.54911522]
avg_loss= [0.02556548]
[1.80623296]x+[0.54905072]
avg_loss= [0.02555476]
[1.80631359]x+[0.54898609]
avg_loss= [0.0255441]
[1.80639377]x+[0.54892132]
avg_loss= [0.02553349]
[1.80647352]x+[0.54885641]
avg_loss= [0.02552293]
[1.80655282]x+[0.54879137]
avg_loss= [0.02551242]
[1.8066317]x+[0.5487262]
avg_loss= [0.02550196]
[1.80671015]x+[0.54866089]
avg_loss= [0.02549156]
[1.80678817]x+[0.54859546]
avg_loss= [0.0254812]
[1.80686577]x+[0.54852989]
avg_loss= [0.02547089]
[1.80694295]x+[0.5484642]
avg_loss= [0.02546063]
[1.80701972]x+[0.54839838]
avg_loss= [0.02545042]
[1.80709607]x+[0.54833243]
avg_loss= [0.02544025]
[1.80717202]x+[0.54826636]
avg_loss= [0.02543013]
[1.80724757]x+[0.54820016]
avg_loss= [0.02542005]
[1.80732271]x+[0.54813384]
avg_loss= [0.02541001]
[1.80739745]x+[0.5480674]
avg_loss= [0.02540002]
[1.8074718]x+[0.54800084]
avg_loss= [0.02539008]
[1.80754576]x+[0.54793416]
avg_loss= [0.02538017]
[1.80761933]x+[0.54786736]
avg_los

[1.81552381]x+[0.53720648]
avg_loss= [0.02415888]
[1.81556437]x+[0.53713046]
avg_loss= [0.02415146]
[1.81560481]x+[0.53705442]
avg_loss= [0.02414404]
[1.81564514]x+[0.53697836]
avg_loss= [0.02413663]
[1.81568535]x+[0.53690226]
avg_loss= [0.02412923]
[1.81572546]x+[0.53682615]
avg_loss= [0.02412183]
[1.81576545]x+[0.53675001]
avg_loss= [0.02411443]
[1.81580534]x+[0.53667384]
avg_loss= [0.02410704]
[1.81584511]x+[0.53659766]
avg_loss= [0.02409965]
[1.81588478]x+[0.53652145]
avg_loss= [0.02409227]
[1.81592434]x+[0.53644521]
avg_loss= [0.0240849]
[1.81596379]x+[0.53636896]
avg_loss= [0.02407753]
[1.81600314]x+[0.53629268]
avg_loss= [0.02407016]
[1.81604239]x+[0.53621638]
avg_loss= [0.0240628]
[1.81608153]x+[0.53614006]
avg_loss= [0.02405545]
[1.81612057]x+[0.53606371]
avg_loss= [0.0240481]
[1.8161595]x+[0.53598735]
avg_loss= [0.02404075]
[1.81619834]x+[0.53591096]
avg_loss= [0.02403341]
[1.81623707]x+[0.53583455]
avg_loss= [0.02402607]
[1.81627571]x+[0.53575813]
avg_loss= [0.02401874]
[1.8

In [35]:
a=np.zeros((1,2))
a[0,0]

0.0